export default function DisclaimerPage() {
  return (
    <div className="space-y-6">
      <div className="rounded-2xl ring-1 ring-slate-200 bg-white p-6">
        <div className="flex items-center gap-3 mb-2">
          <span className="inline-flex items-center gap-2 rounded-full ring-1 ring-slate-200 px-3 py-1 text-xs text-slate-600 bg-slate-50">Notice</span>
          <h1 className="text-xl font-semibold text-slate-800">Disclaimer</h1>
        </div>
        <p className="text-slate-600">AYO is an AI trading agent platform. Content and features are provided for informational and educational purposes only and do not constitute financial, investment, tax, or legal advice. You are solely responsible for your investment decisions. Use of AYO is subject to applicable laws and exchange rules.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <section className="rounded-2xl ring-1 ring-slate-200 bg-white p-5">
          <h3 className="font-semibold text-slate-800 mb-2">No Financial Advice</h3>
          <p className="text-slate-600">Signals, backtests, analytics, or automations generated by AYO are not recommendations. Markets are volatile and unpredictable. Always conduct your own research and consider seeking independent professional advice.</p>
        </section>
        <section className="rounded-2xl ring-1 ring-slate-200 bg-white p-5">
          <h3 className="font-semibold text-slate-800 mb-2">No Warranties</h3>
          <p className="text-slate-600">AYO is provided “as is” without warranties of any kind. We do not guarantee uptime, latency, data accuracy, execution quality, profitability, or error-free operation.</p>
        </section>
        <section className="rounded-2xl ring-1 ring-slate-200 bg-white p-5">
          <h3 className="font-semibold text-slate-800 mb-2">Liability</h3>
          <p className="text-slate-600">To the maximum extent permitted by law, AYO is not liable for any direct, indirect, incidental, special, or consequential damages resulting from the use of the platform.</p>
        </section>
      </div>

      <div className="rounded-2xl ring-1 ring-slate-200 bg-white p-5">
        <h3 className="font-semibold text-slate-800 mb-2">Third-Party Services</h3>
        <p className="text-slate-600">AYO integrates with third-party services such as the Hyperliquid decentralized exchange. We do not control third-party systems and are not responsible for their performance, security, availability, or policies.</p>
      </div>
    </div>
  );
}


